book_abbreviations = {
  "genesis": "Gen",
  "exodus": "Exo",
  "leviticus": "Lev",
  "numbers": "Num",
  "deuteronomy": "Deu",
  "joshua": "Jos",
  "judges": "Jdg",
  "ruth": "Rth",
  "1 samuel": "1Sa",
  "i samuel": "1Sa",
  "2 samuel": "2Sa",
  "ii samuel": "2Sa",
  "1 kings": "1Ki",
  "i kings": "1Ki",
  "2 kings": "2Ki",
  "ii kings": "2Ki",
  "1 chronicles": "1Ch",
  "i chronicles": "1Ch",
  "2 chronicles": "2Ch",
  "ii chronicles": "2Ch",
  "ezra": "Eza",
  "nehemiah": "Neh",
  "esther": "Est",
  "job": "Job",
  "psalms": "Psa",
  "psalm": "Psa",
  "proverbs": "Pro",
  "ecclesiastes": "Ecc",
  "song of solomon": "SS",
  "song of songs": "SS",
  "isaiah": "Isa",
  "jeremiah": "Jer",
  "lamentations": "Lam",
  "ezekiel": "Ezk",
  "daniel": "Dan",
  "hosea": "Hos",
  "joel": "Joe",
  "amos": "Amo",
  "obadiah": "Obd",
  "jonah": "Jon",
  "micah": "Mic",
  "nahum": "Nah",
  "habakkuk": "Hab",
  "zephaniah": "Zep",
  "haggai": "Hag",
  "zechariah": "Zch",
  "malachi": "Mal",
  "matthew": "Mat",
  "mark": "Mrk",
  "luke": "Luk",
  "john": "Jn",
  "acts": "Act",
  "acts of the apostles": "Act",
  "romans": "Rom",
  "1 corinthians": "1Co",
  "i corinthians": "1Co",
  "2 corinthians": "2Co",
  "ii corinthians": "2Co",
  "galatians": "Gal",
  "ephesians": "Eph",
  "philippians": "Php",
  "colossians": "Col",
  "1 thessalonians": "1Th",
  "i thessalonians": "1Th",
  "2 thessalonians": "2Th",
  "ii thessalonians": "2Th",
  "1 timothy": "1Ti",
  "i timothy": "1Ti",
  "2 timothy": "2Ti",
  "ii timothy": "2Ti",
  "titus": "Tit",
  "philemon": "Phm",
  "hebrews": "Heb",
  "james": "Jam",
  "1 peter": "1Pe",
  "i peter": "1Pe",
  "2 peter": "2Pe",
  "ii peter": "2Pe",
  "1 john": "1Jo",
  "i john": "1Jo",
  "2 john": "2Jo",
  "ii john": "2Jo",
  "3 john": "3Jo",
  "iii john": "3Jo",
  "jude": "Jud",
  "revelation": "Rev",
}

books = [
  "Genesis",
  "1 Peter",
  "James",
  "Hebrews",
  "Philemon",
  "Titus",
  "2 Timothy",
  "1 Timothy",
  "2 Thessalonians",
  "1 Thessalonians",
  "Colossians",
  "Philippians",
  "Ephesians",
  "Galatians",
  "2 Corinthians",
  "1 Corinthians",
  "Romans",
  "Acts",
  "John",
  "Luke",
  "Mark",
  "Matthew",
  "Malachi",
  "Zechariah",
  "Haggai",
  "Zephaniah",
  "Habakkuk",
  "Nahum",
  "Micah",
  "Jonah",
  "Obadiah",
  "Amos",
  "Joel",
  "Hosea",
  "Daniel",
  "Ezekiel",
  "Lamentations",
  "Jeremiah",
  "Isaiah",
  "Song of Solomon",
  "Ecclesiastes",
  "Proverbs",
  "Psalms",
  "Job",
  "Esther",
  "Nehemiah",
  "Ezra",
  "2 Chronicles",
  "1 Chronicles",
  "2 Kings",
  "1 Kings",
  "2 Samuel",
  "1 Samuel",
  "Ruth",
  "Judges",
  "Joshua",
  "Deuteronomy",
  "Numbers",
  "Leviticus",
  "Exodus",
]

abbv_to_full = {
  "GEN": "Genesis",
  "EXO": "Exodus",
  "LEV": "Leviticus",
  "NUM": "Numbers",
  "DEU": "Deuteronomy",
  "JOS": "Joshua",
  "JDG": "Judges",
  "RUT": "Ruth",
  "1SA": "1 Samuel",
  "2SA": "2 Samuel",
  "1KI": "1 Kings",
  "2KI": "2 Kings",
  "1CH": "1 Chronicles",
  "2CH": "2 Chronicles",
  "EZR": "Ezra",
  "NEH": "Nehemiah",
  "EST": "Esther",
  "JOB": "Job",
  "PSA": "Psalms",
  "PRO": "Proverbs",
  "ECC": "Ecclesiastes",
  "SOS": "Song of Solomon",
  "ISA": "Isaiah",
  "JER": "Jeremiah",
  "LAM": "Lamentations",
  "EZE": "Ezekiel",
  "DAN": "Daniel",
  "HOS": "Hosea",
  "JOE": "Joel",
  "AMO": "Amos",
  "OBA": "Obadiah",
  "JON": "Jonah",
  "MIC": "Micah",
  "NAH": "Nahum",
  "HAB": "Habakkuk",
  "ZEP": "Zephaniah",
  "HAG": "Haggai",
  "ZEC": "Zechariah",
  "MAL": "Malachi",
  "MAT": "Matthew",
  "MAR": "Mark",
  "LUK": "Luke",
  "JOH": "John",
  "ACT": "Acts",
  "ROM": "Romans",
  "1CO": "1 Corinthians",
  "2CO": "2 Corinthians",
  "GAL": "Galatians",
  "EPH": "Ephesians",
  "PHP": "Philippians",
  "COL": "Colossians",
  "1TH": "1 Thessalonians",
  "2TH": "2 Thessalonians",
  "1TI": "1 Timothy",
  "2TI": "2 Timothy",
  "TIT": "Titus",
  "PHM": "Philemon",
  "HEB": "Hebrews",
  "JAM": "James",
  "1PE": "1 Peter",
  "2PE": "2 Peter",
  "1JO": "1 John",
  "2JO": "2 John",
  "3JO": "3 John",
  "JDE": "Jude",
  "REV": "Revelation",
}